require 'neovim_base_settings.keymaps'
require 'neovim_base_settings.window_management'
require 'neovim_base_settings.options'
require 'neovim_base_settings.auto_cmd'
require 'neovim_base_settings.jumplist'
require 'lazy_plugin_manager'
